import { text } from "@fortawesome/fontawesome-svg-core";

const productsData = {
  product: [
    {
      id: "1",
      name: "HP Smartchoice Victus, 13th Gen Intel Core i5-13420H, 4GB RTX 3050, 16GB DDR4(Upgradeable) 512GB SSD, 144Hz, 300nits, FHD, 15.6’’/39.6cm, Win11, Office24, Blue, 2.29kg, fa2190/fa2191tx Gaming Laptop",
      newprice: 67999,
      oldprice: 72000,
      globalrating: 12843,
      ratingcount: 4,
      rating: 4,
      // quantity: 1,
      smallimageUrl: [
        "https://m.media-amazon.com/images/I/71wT57gW0hL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/61WFCYG1eVL.jpg",
        "https://m.media-amazon.com/images/I/810mcIf6EjL._SL1500_.jpg",
        "https://m.media-amazon.com/images/I/81jSDi+uh9L._SL1500_.jpg",
        "https://m.media-amazon.com/images/I/71wjUK83IRL._SL1500_.jpg",
        "https://m.media-amazon.com/images/I/817eJNOlxLL._SL1500_.jpg",
        "https://m.media-amazon.com/images/I/71szcBKC9zL._SL1500_.jpg",
      ],
      imageUrl: "https://m.media-amazon.com/images/I/71wT57gW0hL._SY450_.jpg",
      offer: ["No Cost EMI", "Cashback", "Bank Offer", "Partner Offers"],
      services: [
        {
          icon: "replace",
          text: "10 Days Replacement by Brand",
        },
        {
          icon: "Delivery",
          text: "Free Delivery",
        },
        {
          icon: "secure",
          text: "1 Year Warrenty",
        },
        {
          icon: "dollar",
          text: "Pay on Delivery",
        },
        {
          icon: "brand",
          text: "Top Brand",
        },
        {
          icon: "lock",
          text: "Secure transaction",
        },
      ],
      about: [
        "Processor, Memory & Storage: Intel Core i5-13420H (up to 4.6 GHz with Intel Turbo Boost Technology, 12 MB L3 cache, 8 cores, 12 threads)| Memory: 16 GB DDR4-3200 MT/s (1 x 16 GB)| Storage: 512 GB PCIe Gen4 NVMe M.2 SSD",
        "Operating System & Preinstalled Software: Windows 11 Home | MS Office Home 2024 |1 year Microsoft 365 Basic Free",
        "Display & Graphics: 39.6 cm (15.6) diagonal, FHD (1920 x 1080), 144 Hz, IPS, micro-edge, anti-glare, 300 nits, 62.5% sRGB| Graphics: NVIDIA GeForce RTX 3050 Laptop GPU (4 GB GDDR6 dedicated)",
        "Ports & Connectivity : 1 USB Type-A 5Gbps signaling rate (HP Sleep and Charge); 1 USB Type-A 5Gbps signaling rate; 1 AC smart pin; 1 HDMI 2.1; 1 headphone/microphone combo; 1 RJ-45; 1 USB Type-C 5Gbps signaling rate (DisplayPort 1.4a, HP Sleep and Charge)| Connectivity: Realtek Wi-Fi 6 (2x2) and Bluetooth 5.4 wireless card",
        "Backlit keyboard with premium gaming design and enhanced cooling system",
        "Other Features: Camera: HP Wide Vision 720p HD camera with temporal noise reduction and integrated dual array digital microphones| Keyboard: Full-size, backlit, performance blue opaque keyboard with numeric keypad| Audio: DTS:X Ultra; Dual speakers; HP Audio Boost",
      ],
    },
    {
      id: "2",
      name: "Boat Airdopes 141 Gen 2 (2025), 4 Mics ENx Tech, 48 Hrs Playback, Free Music Streaming, Fast Charge, Low Latency, IPX4, v5.4 Bluetooth Earbuds, TWS Ear Buds Wireless Earphones with mic (Active Black)",
      newprice: 1299,
      oldprice: 1499,
      globalrating: 12843,
      ratingcount: 5,
      rating: 5,
      quantity: 1,
      seller: "Clicktech Retail Private Ltd",
      smallimageUrl: [
        "https://m.media-amazon.com/images/I/31Clxhds78L._SX450_.jpg",
        "https://m.media-amazon.com/images/I/71xfBj4k-tL._SX450_.jpg",
        "https://m.media-amazon.com/images/I/61jyfmL8G2L._SX466_.jpg",
        "https://m.media-amazon.com/images/I/41Ob2pLZL9L.jpg",
        "https://m.media-amazon.com/images/I/41jnNR4FQtL._SX450_.jpg",
        "https://m.media-amazon.com/images/I/41GDt0FFVQL._SY450_.jpg",
      ],
      imageUrl: "https://m.media-amazon.com/images/I/31Clxhds78L._SX450_.jpg",
      offer: ["No Cost EMI", "Cashback", "Bank Offer", "Partner Offers"],
      services: [
        {
          icon: "replace",
          text: "10 Days Replacement by Brand",
        },
        {
          icon: "Delivery",
          text: "Free Delivery",
        },
        {
          icon: "secure",
          text: "1 Year Warrenty",
        },
        {
          icon: "dollar",
          text: "Pay on Delivery",
        },
        {
          icon: "brand",
          text: "Top Brand",
        },
        {
          icon: "lock",
          text: "Secure transaction",
        },
      ],
      about: [
        "Immersive Stereo Sound Experience – Enjoy deep bass, balanced mids, and crisp highs for music, movies, podcasts, and gaming.",
        "Portable & Stylish Design – Sleek, modern design with pocket-friendly charging case makes these earbuds perfect for travel, workouts, and daily use.",
        "360 AUDIO - Hear it like you're there. With Intelligent 360 Audio, the sound feels more realistic.The 360 Audio algorithms with Direct multichannel (5.1ch / 7.1ch / Dolby Atmos) and Enhanced Dolby Head Tracking make every movement stay in sync — creating an immersive experience. 360 Audio can even pinpoint the direction of the sound as you move your head, giving you the spatial experience",
        "Get up to 5 hrs of continuous playtime with ANC on and up to 18 hrs in the cradle. Buds2 Pro run on Bluetooth v5.3 and are IPX7 water resistant.",
        "AI is here! With interpretation and live translation features, enjoy conversations even more. Break down language barriers like never before and communicate in the language you love.",
      ],
    },
    {
      id: "3",
      name: "Boat Immortal Katana Blade 2.0 TWS in Ear Earbuds, 70hrs Playback, IWP, Metal Glider & Gliding Blade Sound, 50 ms Low Latency Beast Mode, RGB LEDs, 4 Mics w/ENx & IPX4 Rating(Gunmetal Black)",
      newprice: 999,
      oldprice: 1200,
      globalrating: 12843,
      ratingcount: 3,
      rating: 3,
      quantity: 1,
      seller: "Wave Tone",
      smallimageUrl: [
        "https://m.media-amazon.com/images/I/71m8EO4VzfL._SX466_.jpg",
        "https://m.media-amazon.com/images/I/71-wf-xsjkL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/81dPnDlPpnL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/71ZzA1liIVL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/71+1-mm8GTL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/71Rt70c-xKL._SY450_.jpg",
      ],
      imageUrl: "https://m.media-amazon.com/images/I/71m8EO4VzfL._SX466_.jpg",
      offer: ["No Cost EMI", "Cashback", "Bank Offer", "Partner Offers"],
      services: [
        {
          icon: "replace",
          text: "10 Days Replacement by Brand",
        },
        {
          icon: "Delivery",
          text: "Free Delivery",
        },
        {
          icon: "secure",
          text: "1 Year Warrenty",
        },
        {
          icon: "dollar",
          text: "Pay on Delivery",
        },
        {
          icon: "brand",
          text: "Top Brand",
        },
        {
          icon: "lock",
          text: "Secure transaction",
        },
      ],
      about: [
        "Insta Wake N‘Pair (IWP) with Metal Glider: Make a mark in the virtual battleground instantly with the boAt Immortal Katana Blade 2.0 TWS Earbuds. Designed with a metal glider, these earbuds are sure to steal everyone’s attention. Make use of IWP and connect in no time by sliding the case open.",
        "50ms Latency BEAST Mode: Race through hurdles seamlessly with the 50 ms low latency of BEAST mode. Enjoy sync-ed frames and audio for realistic gaming.",
        "Attractive RGB LEDs: Amp your gaming setup with the RGB lights on these earbuds. Your digital moves are relayed with eye-catching light effects that lend a pro-gamer vibe.",
        "Massive 70 Hours Playback: Immortal Katana Blade 2.0 is here to redefine your experience! Enjoy up to 70 hours of gaming or streaming without low battery woes.",
        "boAt Signature Sound: Along with two 10 mm drivers, these earbuds kick audio output up a notch with the rich bass and sharp treble of boAt Signature Sound from the two drivers.",
        "ASAP Charge: Forget low battery levels playing spoilsport to your fun. With ASAP Charge, get a boost of up to 180 minutes after charging your buds for 10 minutes.",
        "4 Mics with ENx Technology: Speak and hear on calls whether you are indoors or on the go. Be it an airport lounge, a cafe, or a busy street, the quad mics in these earbuds sport ENx tech that cancels surrounding noise for high clarity on calls.",
        "Bluetooth v5.3: Experience heightened wireless comfort with these earbuds. Bluetooth v5.3 compatibility offers reliable connectivity for up to 10 m making it effortless to stay entertained.",
        "Gliding Blade Sound: Elevate your audio routine with the distinct ‘swish’ sound of your earbuds gliding open.",
        "IPX4 Resistance: Carry your tunes to the gym or the office without worrying about damage as the IPX4 resistance of these earbuds keeps sweat and splashes at bay.",
      ],
    },
    {
      id: "4",
      name: "Apple iPhone 15 (256 GB) - Blue",
      newprice: 79999,
      oldprice: 85000,
      globalrating: 12843,
      ratingcount: 4,
      rating: 4,
      quantity: 1,
      seller: "Clicktech Retails Private Ltd",
      smallimageUrl: [
        "https://m.media-amazon.com/images/I/71d7rfSl0wL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/51wKeZuX6rL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/712CBkmhLhL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/61f4dTush1L._SX679_.jpg",
        "https://m.media-amazon.com/images/I/81BnjSLm2oL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/613xywt-yvL._SX679_.jpg",
      ],
      imageUrl: "https://m.media-amazon.com/images/I/71d7rfSl0wL._SX679_.jpg",
      offer: ["No Cost EMI", "Cashback", "Bank Offer", "Partner Offers"],
      services: [
        {
          icon: "replace",
          text: "10 Days Replacement by Brand",
        },
        {
          icon: "Delivery",
          text: "Free Delivery",
        },
        {
          icon: "secure",
          text: "1 Year Warrenty",
        },
        {
          icon: "dollar",
          text: "Pay on Delivery",
        },
        {
          icon: "brand",
          text: "Top Brand",
        },
        {
          icon: "lock",
          text: "Secure transaction",
        },
      ],
      about: [
        "DYNAMIC ISLAND COMES TO IPHONE 15 — Dynamic Island bubbles up alerts and Live Activities — so you don’t miss them while you’re doing something else. You can see who’s calling, track your next ride, check your flight status, and so much more.",
        "INNOVATIVE DESIGN — iPhone 15 features a durable color-infused glass and aluminum design. It’s splash, water, and dust resistant. The Ceramic Shield front is tougher than any smartphone glass. And the 6.1' Super Retina XDR display is up to 2x brighter in the sun compared to iPhone 14.",
        "48MP MAIN CAMERA WITH 2X TELEPHOTO — The 48MP Main camera shoots in super-high resolution. So it’s easier than ever to take standout photos with amazing detail. The 2x optical-quality Telephoto lets you frame the perfect close-up.",
        "NEXT-GENERATION PORTRAITS — Capture portraits with dramatically more detail and color. Just tap to shift the focus between subjects — even after you take the shot.",
        "POWERHOUSE A16 BIONIC CHIP — The superfast chip powers advanced features like computational photography, fluid Dynamic Island transitions, and Voice Isolation for phone calls. And A16 Bionic is incredibly efficient to help deliver great all-day battery life.",
      ],
    },
    {
      id: "5",
      name: "Redmi Pad 2 Pro [Smartchoice] | 12000mAh | Snapdragon 7s Gen 4 |12.1-inch, 2.5K Display |83+ Days Standby |HyperOS 2 |120Hz| Dolby Vision Atmos | Wi-Fi 6| AI Powered | 8GB,128GB |Graphite Grey",
      newprice: 24999,
      oldprice: 28999,
      globalrating: 12843,
      ratingcount: 4,
      rating: 4,
      quantity: 1,
      seller: "Clicktech Retails Private Ltd",
      smallimageUrl: [
        "https://m.media-amazon.com/images/I/71t0olqGsFL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/81Y7hIURR6L._SY450_.jpg",
        "https://m.media-amazon.com/images/I/81M7eS63o0L._SY450_.jpg",
        "https://m.media-amazon.com/images/I/71BqkWSP38L._SY450_.jpg",
        "https://m.media-amazon.com/images/I/716ffHkothL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/71Sv4YboyIL._SY450_.jpg",
      ],
      imageUrl: "https://m.media-amazon.com/images/I/71t0olqGsFL._SY450_.jpg",
      offer: ["No Cost EMI", "Cashback", "Bank Offer", "Partner Offers"],
      services: [
        {
          icon: "replace",
          text: "10 Days Replacement by Brand",
        },
        {
          icon: "Delivery",
          text: "Free Delivery",
        },
        {
          icon: "secure",
          text: "1 Year Warrenty",
        },
        {
          icon: "dollar",
          text: "Pay on Delivery",
        },
        {
          icon: "brand",
          text: "Top Brand",
        },
        {
          icon: "lock",
          text: "Secure transaction",
        },
      ],
      about: [
        "Upgrade your entertainment and productivity with the Redmi Pad 2 Pro, designed for power and performance on the go. Enjoy a stunning 30.73 cm(12.1) 2.5K display with a super-smooth 120Hz AdaptiveSync refresh rate and Dolby Vision for lifelike colours and clarity.",
        "Stay connected everywhere with Wi-Fi 6, and experience seamless multi-device workflow through HyperOS 2, which lets you access phone apps, sync calls, share clipboard content, and switch networks effortlessly.",
        "Powered by the Snapdragon 7s Gen 4, this tablet handles multitasking, gaming, classes and office work with ease. Store more with expandable storage up to 2TB. The massive 12000mAh battery delivers all-day endurance for streaming, studying, creating and more.",
        "Immersive quad speakers with Dolby Atmos make movies, music and games sound bigger and richer. Pair it with the Redmi Smart Pen (sold separately) for natural writing and sketching, or the Redmi Pad 2 Pro Keyboard (sold separately) to turn your tablet into a productivity powerhouse.",
      ],
    },
    {
      id: "6",
      name: "Dell KM7321W Premier Multi-Device Wireless Keyboard & Mouse, Volume, Mute Hot Keys, International English, Scissors Technology, 7 Buttons, 1600 DPI, AA x 1 Battery, Bluetooth 5.0",
      newprice: 5884,
      oldprice: 2499,
      globalrating: 12843,
      ratingcount: 4,
      rating: 4,
      quantity: 1,
      seller: "Clicktech Retails Private Ltd",
      smallimageUrl: [
        "https://m.media-amazon.com/images/I/714P1XbGl4S._SY450_.jpg",
        "https://m.media-amazon.com/images/I/715AtDls7IS._SY450_.jpg",
        "https://m.media-amazon.com/images/I/71KMesFvMzS._SY450_.jpg",
        "https://m.media-amazon.com/images/I/81NriEvk21S._SY450_.jpg",
        "https://m.media-amazon.com/images/I/7122CeNAuNS._SY450_.jpg",
        "https://m.media-amazon.com/images/I/71N9WFOtaBS._SY450_.jpg",
      ],
      imageUrl: "https://m.media-amazon.com/images/I/714P1XbGl4S._SY450_.jpg",
      offer: ["No Cost EMI", "Cashback", "Bank Offer", "Partner Offers"],
      services: [
        {
          icon: "replace",
          text: "10 Days Replacement by Brand",
        },
        {
          icon: "Delivery",
          text: "Free Delivery",
        },
        {
          icon: "secure",
          text: "1 Year Warrenty",
        },
        {
          icon: "dollar",
          text: "Pay on Delivery",
        },
        {
          icon: "brand",
          text: "Top Brand",
        },
        {
          icon: "lock",
          text: "Secure transaction",
        },
      ],
      about: [
        "CORE PERFORMANCE – Seamless typing with 7‑button scissor‑switch keyboard and precise 1600 DPI optical mouse for accurate cursor control.",
        "COMPATIBILITY – Connect instantly via 2.4 GHz dongle or Bluetooth 5.0 to Windows, macOS, Chrome OS or Linux, with USB receiver and AA & 2 AAA batteries supplied.",
        "VISUAL EXPERIENCE – Experience smooth cursor movement and precise tracking with 1600 DPI optical sensor, enhancing productivity on any screen.",
        "BATTERY LIFE – Enjoy up to 36 months of battery life on both devices, powered by included AA and AAA batteries, with reliable wireless performance.",
        "COMFORT - Slim Titan‑grey combo weighs under 650 g, featuring volume/mute hot‑keys and a durable scissor‑switch layout for comfortable all‑day typing.",
      ],
    },
    {
      id: "7",
      name: "HP H200 Wireless Headset",
      newprice: 1299,
      oldprice: 3749,
      globalrating: 12843,
      ratingcount: 5,
      rating: 5,
      quantity: 1,
      seller: "Clicktech Retails Private Ltd",
      smallimageUrl: [
        "https://m.media-amazon.com/images/I/71Yl4L6JVML._SY450_.jpg",
        "https://m.media-amazon.com/images/I/714U6QaISqL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/71ose7SMU8L._SY450_.jpg",
        "https://m.media-amazon.com/images/I/7182XHja8KL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/71cO+DdjsAL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/71B+ix-YXSL._SY450_.jpg",
      ],
      imageUrl:
        "https://m.media-amazon.com/images/I/31rO8ifdICL._AC_SR480,440_.jpg",
      offer: ["No Cost EMI", "Cashback", "Bank Offer", "Partner Offers"],
      services: [
        {
          icon: "replace",
          text: "10 Days Replacement by Brand",
        },
        {
          icon: "Delivery",
          text: "Free Delivery",
        },
        {
          icon: "secure",
          text: "1 Year Warrenty",
        },
        {
          icon: "dollar",
          text: "Pay on Delivery",
        },
        {
          icon: "brand",
          text: "Top Brand",
        },
        {
          icon: "lock",
          text: "Secure transaction",
        },
      ],
      about: [
        "[Goodbye background noise] : Enjoy a more immersive audio experience and clearer calls, even in noisy environments, using the built-in mic with Digital Signal Processor.",
        "[Connectivity far and wide] : :Connect far and wide using BT V5.3 with 2x the speed and 4x the range.",
        "[Easy charging, more listening.] : Enjoy easy plug and play with the Type-C port, designed for optimal charging.",
      ],
    },
    {
      id: "8",
      name: "Fire-Boltt Ninja Call Pro Plus Bluetooth Calling Smart Watch, 1.83″ HD Display, AI Voice Assistant, 120+ Sports Modes, IP67 Waterproof, SpO2 & Heart Rate Monitor Smartwatch for Men & Women - Black",
      newprice: 1199,
      oldprice: 19999,
      globalrating: 12843,
      ratingcount: 4,
      rating: 4,
      quantity: 1,
      seller: "Clicktech Retails Private Ltd",
      smallimageUrl: [
        "https://m.media-amazon.com/images/I/61rmkmqD5VL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/71uVFWWZigL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/717ayT6vKyL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/71GsTAibaFL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/615S9dKuyiL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/81ubHkssi7L._SY450_.jpg",
      ],
      imageUrl: "https://m.media-amazon.com/images/I/61rmkmqD5VL._SY450_.jpg",
      offer: ["No Cost EMI", "Cashback", "Bank Offer", "Partner Offers"],
      services: [
        {
          icon: "replace",
          text: "10 Days Replacement by Brand",
        },
        {
          icon: "Delivery",
          text: "Free Delivery",
        },
        {
          icon: "secure",
          text: "1 Year Warrenty",
        },
        {
          icon: "dollar",
          text: "Pay on Delivery",
        },
        {
          icon: "brand",
          text: "Top Brand",
        },
        {
          icon: "lock",
          text: "Secure transaction",
        },
      ],
      about: [
        "LARGE 1.83” HD DISPLAY WITH BRIGHT VISIBILITY – Enjoy a stunning 1.83-inch HD screen with 280 NITS peak brightness and vivid color clarity. Whether indoors or outdoors, with smart watch for woman experience sharp visuals and smooth touch interaction all day long.",
        "EXTENDED BATTERY LIFE FOR NON-STOP USAGE – Stay connected longer with a power-efficient battery of premium smart watch for men that lasts for days on a single charge. Ideal for work, travel, and workouts—no need to worry about frequent charging.",
        "BLUETOOTH CALLING ON YOUR WRIST – Smart watch for men make and receive calls directly from your smartwatch with crystal-clear audio. Perfect for busy professionals, fitness lovers, and on-the-go users who want phone-free communication.",
        "SMART AI VOICE ASSISTANT FOR HANDS-FREE CONTROL – Use voice commands to check the weather, play music, set reminders, and manage tasks. The built-in AI voice assistant of ai smart watch delivers convenience for your daily routine.",
        "ALL-IN-ONE FITNESS & HEALTH TRACKING FEATURES – Track your steps, heart rate, SpO2, calories, sleep, and more. With fitness tracker smart watch for men, multiple sports modes, sedentary reminders, and daily workout memory, smart watch for women your ultimate fitness companion as fitness watch",
        "MULTIPLE SMART FEATURES & IP67 WATER RESISTANCE – Includes built-in mic & speaker, alarm, games, music player, notifications, find phone, time display, and IP67 rating for water and dust resistance. Built for every lifestyle.",
      ],
    },
    {
      id: "9",
      name: "JBL C100SI Wired In Ear Headphones With Mic, Pure Bass Sound, One Button Multi-Function Remote, Premium Metallic Finish, Angled Buds For Comfort Fit (Black)",
      newprice: 599,
      oldprice: 1299,
      globalrating: 12843,
      ratingcount: 5,
      rating: 5,
      quantity: 1,
      seller: "Clicktech Retails Private Ltd",
      smallimageUrl: [
        "https://m.media-amazon.com/images/I/31NnmYempPL._AC_SR480,440_.jpg",
        "https://m.media-amazon.com/images/I/91kcPKEG-NL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/91iPKswDKVL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/91D78FlIBIL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/91ZEFiUZVXL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/81n1wy0yAwL._SY450_.jpg",
      ],
      imageUrl:
        "https://m.media-amazon.com/images/I/31NnmYempPL._AC_SR480,440_.jpg",
      offer: ["No Cost EMI", "Cashback", "Bank Offer", "Partner Offers"],
      services: [
        {
          icon: "replace",
          text: "10 Days Replacement by Brand",
        },
        {
          icon: "Delivery",
          text: "Free Delivery",
        },
        {
          icon: "secure",
          text: "1 Year Warrenty",
        },
        {
          icon: "dollar",
          text: "Pay on Delivery",
        },
        {
          icon: "brand",
          text: "Top Brand",
        },
        {
          icon: "lock",
          text: "Secure transaction",
        },
      ],
      about: [
        "JBL Signature Sound",
        "Lightweight and Comfortable : The 3 sizes of ear tips (S,M,L) that are included allow you to choose a size that gives you the most comfortable listening experience even for longer listening periods",
        "1 year manufacturer’s warranty. Cable Length: 1.2M",
        "JBL Signature Sound. Frequency range:20-20kHz,Driver sensitivity:100±3dBSPL, 1mW,Maximum SPL:5mW",
        "Extra Deep Bass. Troubleshooting steps : Kindly ensure 3.5mm port on Host device is clean and dust free and 3.5mm jack of the earphone is adequately inserted inside the input device port",
        "Noise Cancelling Microphone",
        "One-Button Universal Remote with Mic",
        "Quick Launch Access to Google Assistant / Siri",
        "Sleek, Glossy & Ergonomic design",
        "What's in the box : 1 pair JBL C100SI headphone, 3 sets of ear tips (S, M, L), 1 Warranty and safety card",
      ],
    },
    {
      id: "10",
      name: "Boat Bassheads 900 Pro Wired Headphones with 40Mm Drivers, Lightweight Foldable Design, Over Ear, Remote Control, Unidirectional Retractable Mic, Adjustable Headband & USB Type-A Compatibility(Black)",
      newprice: 999,
      oldprice: 4999,
      globalrating: 12843,
      ratingcount: 4,
      rating: 4,
      quantity: 1,
      seller: "Clicktech Retails Private Ltd",
      smallimageUrl: [
        "https://m.media-amazon.com/images/I/4192vscwlSL._AC_SR480,440_.jpg",
        "https://m.media-amazon.com/images/I/71vQxVpXaOL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/71lK-WCRvdL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/61xvPqxlqEL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/71cr77vEx3L._SY450_.jpg",
        "https://m.media-amazon.com/images/I/717rLNYK-+L._SY450_.jpg",
      ],
      imageUrl:
        "https://m.media-amazon.com/images/I/4192vscwlSL._AC_SR480,440_.jpg",
      offer: ["No Cost EMI", "Cashback", "Bank Offer", "Partner Offers"],
      services: [
        {
          icon: "replace",
          text: "10 Days Replacement by Brand",
        },
        {
          icon: "Delivery",
          text: "Free Delivery",
        },
        {
          icon: "secure",
          text: "1 Year Warrenty",
        },
        {
          icon: "dollar",
          text: "Pay on Delivery",
        },
        {
          icon: "brand",
          text: "Top Brand",
        },
        {
          icon: "lock",
          text: "Secure transaction",
        },
      ],
      about: [
        "40mm Drivers: Plug in the boAt BassHeads 900 Pro Wired Headphones and enter the audio realm with 40 mm drivers that lend crisp audio. Be it gaming or indulging in OTT content, these headphones are your perfect audio companion.",
        "Lightweight Build: Stay comfortable wearing these headphones for long hours, courtesy of the lightweight design.",
        "Remote Control: Use the inline controls to scroll and adjust the volume to your desired level. Additionally, you can mute or unmute the sound with the handy mute control switch.",
        "Unidirectional Mic: Featuring a unidirectional microphone, BassHeads 900 Pro is ideal for having in-game conversations with your squad and online calls.",
        "Foldable Design: Thanks to the foldable design, these headphones occupy minimum space in your audio setup. When not in use, you can fold these headphones easily and stow them away for subsequent usage.",
      ],
    },
    {
      id: "11",
      name: "Boat BassHeads 225 in-Ear Super Extra Bass Wired Headphones, with Mic (Black)",
      newprice: 499,
      oldprice: 999,
      globalrating: 12843,
      ratingcount: 4,
      rating: 4,
      quantity: 1,
      seller: "Clicktech Retails Private Ltd",
      smallimageUrl: [
        "https://m.media-amazon.com/images/I/318BcYFpRdL._AC_SR480,440_.jpg",
        "https://m.media-amazon.com/images/I/81lItXPSimL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/71y2TqQIsNL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/71p98rdJyoL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/71IUCpkKlzL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/61R5U8oCW2L._SY450_.jpg",
      ],
      imageUrl:
        "https://m.media-amazon.com/images/I/318BcYFpRdL._AC_SR480,440_.jpg",
      offer: ["No Cost EMI", "Cashback", "Bank Offer", "Partner Offers"],
      services: [
        {
          icon: "replace",
          text: "10 Days Replacement by Brand",
        },
        {
          icon: "Delivery",
          text: "Free Delivery",
        },
        {
          icon: "secure",
          text: "1 Year Warrenty",
        },
        {
          icon: "dollar",
          text: "Pay on Delivery",
        },
        {
          icon: "brand",
          text: "Top Brand",
        },
        {
          icon: "lock",
          text: "Secure transaction",
        },
      ],
      about: [
        "Innovative housing design enables for easy adjustment and optimal wearing comfort with powerful 10mm drivers for sonic clarity, bass-driven stereo sound and good attenuation of ambient noise",
        "The noise-cancelling microphone enables trouble free receiving of calls or undeterred sessions of musical extravaganza",
        "Made to fit you and your lifestyle, providing a smooth grip for an extra secure and comfortable fit for your ears",
        "Passive noise cancellation feature enables users to enjoy listening to your music in a chaotic and noisy environment, it also enables users to receive calls on-the-go",
        "Crafted with care, the polished metal ensures its longevity",
      ],
    },
    {
      id: "12",
      name: "Digitek (DCR-007) USB-A 3.0 & Type C High-Speed Multi-Card Reader Supports All Standard SD/SDHC/SDXC and Micro SD/SDHC/SDXC Cards",
      newprice: 299,
      oldprice: 599,
      globalrating: 12843,
      ratingcount: 5,
      rating: 5,
      quantity: 1,
      seller: "Clicktech Retails Private Ltd",
      smallimageUrl: [
        "https://m.media-amazon.com/images/I/31IjbPtnF7L._AC_SR480,440_.jpg",
        "https://m.media-amazon.com/images/I/61+WvVQbbNL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/51d6PB1VhxL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/61GHLBd-8fL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/61cralrDtBL._SY450_.jpg",
        "https://m.media-amazon.com/images/I/61E7HD+xcWL._SY450_.jpg",
      ],
      imageUrl:
        "https://m.media-amazon.com/images/I/31IjbPtnF7L._AC_SR480,440_.jpg",
      offer: ["No Cost EMI", "Cashback", "Bank Offer", "Partner Offers"],
      services: [
        {
          icon: "replace",
          text: "10 Days Replacement by Brand",
        },
        {
          icon: "Delivery",
          text: "Free Delivery",
        },
        {
          icon: "secure",
          text: "1 Year Warrenty",
        },
        {
          icon: "dollar",
          text: "Pay on Delivery",
        },
        {
          icon: "brand",
          text: "Top Brand",
        },
        {
          icon: "lock",
          text: "Secure transaction",
        },
      ],
      about: [
        "        DUAL PORT COMPATIBILITY: Features both USB-A 3.0 and Type C ports, ensuring high-speed data transfer and broad compatibility with a wide range of devices.",
        "SUPPORTS MULTI TYPE CARDS: Compatible with all standard SD, SDHC, SDXC, Micro SD, Micro SDHC, and Micro SDXC cards, making it an ideal solution for photographers, videographers, and everyday users.",
        "TYPE C OTG SUPPPORT: Provides OTG (On-The-Go) functionality, allowing direct reading of SD and T-Flash cards on USB C and OTG-supported devices without the need for additional adapters.",
        "COMPACT & PORTABLE: Designed for easy portability, the compact size of this multi-card reader makes it convenient to carry in your pocket or bag for on-the-go use.",
        "TRANSFORM INTO U FLASH DISK: When used with memory cards, this card reader converts into a U Flash Disk, providing extra storage and seamless access to your data.",
        "HIGH SPEED DATA TRANSFER: Leverages USB 3.0 technology for fast and efficient data transfer, ensuring quick access to your files, photos, and videos.",
      ],
    },
    {
      id: "13",
      name: "DIGITEK® (DRL-14C) 14 Inch LED Ring Light with 5ft Stand & Smartphone Mount - USB Powered, Color Switch Mode, Brightness Control, Dual Temperature - for Photo & Video Shoots, Makeup, Vlogging!",
      newprice: 1299,
      oldprice: 4295,
      globalrating: 12843,
      ratingcount: 3,
      rating: 3,
      quantity: 1,
      seller: "Clicktech Retails Private Ltd",
      smallimageUrl: [
        "https://m.media-amazon.com/images/I/31XNJZx2HoL._AC_SR480,440_.jpg",
        "https://m.media-amazon.com/images/I/61dVrwErUhL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/61Gd4b3HtML._SX679_.jpg",
        "https://m.media-amazon.com/images/I/61w4dqqNIrL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/61TUD8lSOEL._SX679_.jpg",
        "https://m.media-amazon.com/images/I/611fbG544IL._SX679_.jpg",
      ],
      imageUrl:
        "https://m.media-amazon.com/images/I/31XNJZx2HoL._AC_SR480,440_.jpg",
      offer: ["No Cost EMI", "Cashback", "Bank Offer", "Partner Offers"],
      services: [
        {
          icon: "replace",
          text: "10 Days Replacement by Brand",
        },
        {
          icon: "Delivery",
          text: "Free Delivery",
        },
        {
          icon: "secure",
          text: "1 Year Warrenty",
        },
        {
          icon: "dollar",
          text: "Pay on Delivery",
        },
        {
          icon: "brand",
          text: "Top Brand",
        },
        {
          icon: "lock",
          text: "Secure transaction",
        },
      ],
      about: [
        "RING LIGHT WITH USB - High power 10W Ring LED is suitable for most devices that support USB ports, such as laptops, PCs, mobile power, USB chargers, AC adapters, etc.There are four buttons on the selfie ring light, which can be turned on / off, switch the lighting mode and adjust the brightness level, it is easy to find your favorite option in seconds. Ideal for using lighting in the studio, makeup in the locker room, camping, live streaming, etc.",
        "INTELLIGENT AND QUICK COLOR CHANGE - TYGOT makes it easy to adjust the color temperature from 3400K to 5600K easily without using color filters. Achieve cold white light or warm light to hide blemishes and change skin tones quickly and easily. LED SMD design and 220pcs LED beads on our Ring Light offers more light for your camera photography, live streaming, Facebook Live, beauty makeup, selfies and videos.",
        "DIMMABLE LED RING LIGHT - The LED ring light is equipped with 220 high-quality SMD LEDs and 3 different lighting modes (white light, natural light, and warm light), bright enough to beautify your face. Each lighting mode has 9 adjustable brightness levels to meet all your needs on different occasions. This is the perfect dimmable day lighting to eliminate all unpleasant shadows!",
        "EASY TO INSTALL - Ring LED can be easily installed to any light stand or tripod.",
        "PHONE HOLDER AND 7'feet tripod - Each TYGOT Ring Light has a rotating (360 degrees) phone holder and a retractable tripod that effortlessly helps you capture different levels of brightness and angles of lighting! The phone holder is suitable for most smartphones.",
      ],
    },
  ],
};

export default productsData;
